# # 필요한 라이브러리

## ## Chrome(크롬) 드라이버

In [1]:
#이 부분은 처음 한번만 실행하면 됌.
!pip install selenium
!apt-get update
!apt install chromium-chromedriver
!cp /usr/lib/chromium-browser/chromedriver /usr/bin

Requirement already satisfied: selenium in /usr/local/lib/python3.7/dist-packages (4.1.5)
Requirement already satisfied: trio-websocket~=0.9 in /usr/local/lib/python3.7/dist-packages (from selenium) (0.9.2)
Requirement already satisfied: urllib3[secure,socks]~=1.26 in /usr/local/lib/python3.7/dist-packages (from selenium) (1.26.9)
Requirement already satisfied: trio~=0.17 in /usr/local/lib/python3.7/dist-packages (from selenium) (0.20.0)
Requirement already satisfied: idna in /usr/local/lib/python3.7/dist-packages (from trio~=0.17->selenium) (2.10)
Requirement already satisfied: attrs>=19.2.0 in /usr/local/lib/python3.7/dist-packages (from trio~=0.17->selenium) (21.4.0)
Requirement already satisfied: sortedcontainers in /usr/local/lib/python3.7/dist-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: outcome in /usr/local/lib/python3.7/dist-packages (from trio~=0.17->selenium) (1.1.0)
Requirement already satisfied: async-generator>=1.9 in /usr/local/lib/python3.7/dist-packages (from trio~=0.17->selenium) (1.10)
Requirement already satisfied: sniffio in /usr/local/lib/python3.7/dist-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: wsproto>=0.14 in /usr/local/lib/python3.7/dist-packages (from trio-websocket~=0.9->selenium) (1.1.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in /usr/local/lib/python3.7/dist-packages (from urllib3[secure,socks]~=1.26->selenium) (1.7.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.7/dist-packages (from urllib3[secure,socks]~=1.26->selenium) (2021.10.8)
Requirement already satisfied: pyOpenSSL>=0.14 in /usr/local/lib/python3.7/dist-packages (from urllib3[secure,socks]~=1.26->selenium) (22.0.0)
Requirement already satisfied: cryptography>=1.3.4 in /usr/local/lib/python3.7/dist-packages (from urllib3[secure,socks]~=1.26->selenium) (37.0.2)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.7/dist-packages (from cryptography>=1.3.4->urllib3[secure,socks]~=1.26->selenium) (1.15.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.7/dist-packages (from cffi>=1.12->cryptography>=1.3.4->urllib3[secure,socks]~=1.26->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in /usr/local/lib/python3.7/dist-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.13.0)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from h11<1,>=0.9.0->wsproto>=0.14->trio-websocket~=0.9->selenium) (4.2.0)
Hit:1 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease
Hit:2 https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/ InRelease
Ign:3 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
Hit:4 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release
Hit:5 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:6 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:7 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu bionic InRelease
Hit:8 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:9 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
Hit:10 http://ppa.launchpad.net/cran/libgit2/ubuntu bionic InRelease
Hit:11 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu bionic InRelease
Hit:13 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu bionic InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
chromium-chromedriver is already the newest version (101.0.4951.64-0ubuntu0.18.04.1).
The following packages were automatically installed and are no longer required:
  libnvidia-common-460 nsight-compute-2020.2.0
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 74 not upgraded.
cp: '/usr/lib/chromium-browser/chromedriver' and '/usr/bin/chromedriver' are the same file

In [2]:
# -*- coding: UTF-8 -*-
import time
from selenium import webdriver

In [3]:
#Colab에선 웹브라우저 창이 뜨지 않으므로 별도 설정한다.
 
options = webdriver.ChromeOptions()
options.add_argument('--headless')        # Head-less 설정
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')
driver = webdriver.Chrome('chromedriver', options=options)

In [4]:
import pandas as pd

from bs4 import BeautifulSoup

from selenium.webdriver.support.ui import Select

from time import sleep

# # 정리

## ## [타자 데이터]

In [9]:
def getAllDataHitter(year = 2022)  :
  """
  # year = 검색할 연도
  """

  driver.get("https://www.koreabaseball.com/Record/Team/Hitter/Basic1.aspx")

  dropdown = Select(driver.find_element_by_id('cphContents_cphContents_cphContents_ddlSeason_ddlSeason'))
  dropdown.select_by_value(f"{year}")

  sleep(10)

  html = driver.page_source

  # 파서
  soup = BeautifulSoup(html, "html.parser")

  # 컬럼명 추출
  columns_all = list()

  for i in soup.select("th")[1:] :
    columns_all.append(i.text)

  # 팀명 추출
  team = list()

  for i_team_list in range(1,len(soup.select("tr"))-1) :
    team_xpath = driver.find_element_by_xpath(f"//*[@id='cphContents_cphContents_cphContents_udpContent']/div[2]/table/tbody/tr[{i_team_list}]/td[2]")
    team.append(team_xpath.text)

  # 추출할 td 목록
  td_list_1 = ["team"
              , "HRA_RT"
              , "GAME_CN"
              , "PA_CN"
              , "AB_CN"
              , "RUN_CN"
              , "HIT_CN"
              , "H2_CN"
              , "H3_CN"
              , "HR_CN"
              , "TB_CN"
              , "RBI_CN"
              , "SH_CN"
              , "SF_CN"
              ]
    
  # 각 수치 변수에 넣기
  HRA_RT = list()
  GAME_CN = list()
  PA_CN = list()
  AB_CN = list()
  RUN_CN = list()
  HIT_CN = list()
  H2_CN = list()
  H3_CN = list()
  HR_CN = list()
  TB_CN = list()
  RBI_CN = list()
  SH_CN = list()
  SF_CN = list()

  for idx in td_list_1 :
    for i in range(len(soup.select(f"[data-id='{idx}']"))) :
      if idx == "HRA_RT" :
        HRA_RT.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "GAME_CN" :
        GAME_CN.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "PA_CN" :
        PA_CN.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "AB_CN" :
        AB_CN.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "RUN_CN" :
        RUN_CN.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "HIT_CN" :
        HIT_CN.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "H2_CN" :
        H2_CN.append(soup.select(f"[data-id='{idx}']")[i].text) 
      elif idx == "H3_CN" :
        H3_CN.append(soup.select(f"[data-id='{idx}']")[i].text)  
      elif idx == "HR_CN" :
        HR_CN.append(soup.select(f"[data-id='{idx}']")[i].text)  
      elif idx == "TB_CN" :
        TB_CN.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "RBI_CN" :
        RBI_CN.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "SH_CN" :
        SH_CN.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "SF_CN" :
        SF_CN.append(soup.select(f"[data-id='{idx}']")[i].text)

  # 데이터 프레임으로 만들기
  all_data_hitter_1 = pd.DataFrame(data = list(zip(team
                                          ,HRA_RT
                                          ,GAME_CN
                                          ,PA_CN
                                          ,AB_CN
                                          ,RUN_CN
                                          ,HIT_CN
                                          ,H2_CN
                                          ,H3_CN
                                          ,HR_CN
                                          ,TB_CN
                                          ,RBI_CN
                                          ,SH_CN
                                          ,SF_CN))
                        , columns = columns_all
                        ).set_index('팀명')

  # 2페이지 
  driver.get("https://www.koreabaseball.com/Record/Team/Hitter/Basic2.aspx")

  dropdown = Select(driver.find_element_by_id('cphContents_cphContents_cphContents_ddlSeason_ddlSeason'))
  dropdown.select_by_value(f"{year}")

  sleep(10)

  html = driver.page_source
  soup = BeautifulSoup(html, "html.parser")

  td_list_2 = ["team"
              , "HRA_RT"
              , "BB_CN"
              , "IB_CN"
              , "HP_CN"
              , "KK_CN"
              , "GD_CN"
              , "SLG_RT"
              , "OBP_RT"
              , "OPS_RT"
              , "MH_HITTER_CN"
              , "SP_HRA_RT"
              , "PH_HRA_RT"
              ]

  HRA_RT =list()
  BB_CN= list()
  IB_CN= list()
  HP_CN= list()
  KK_CN= list()
  GD_CN= list()
  SLG_RT= list()
  OBP_RT= list()
  OPS_RT= list()
  MH_HITTER_CN= list()
  SP_HRA_RT= list()
  PH_HRA_RT= list()

  for idx in td_list_2 :
    for i in range(len(soup.select(f"[data-id='{idx}']"))) :
      if idx == "BB_CN" :
        BB_CN.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "HRA_RT" :
        HRA_RT.append(soup.select(f"[data-id='{idx}']")[i].text)    
      elif idx == "IB_CN" :
        IB_CN.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "HP_CN" :
        HP_CN.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "KK_CN" :
        KK_CN.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "GD_CN" :
        GD_CN.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "SLG_RT" :
        SLG_RT.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "OBP_RT" :
        OBP_RT.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "OPS_RT" :
        OPS_RT.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "MH_HITTER_CN" :
        MH_HITTER_CN.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "SP_HRA_RT" :
        SP_HRA_RT.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "PH_HRA_RT" :
        PH_HRA_RT.append(soup.select(f"[data-id='{idx}']")[i].text)

  # 컬럼명 추출
  columns_all = list()

  for i in soup.select("th")[1:] :
    columns_all.append(i.text)
  
  all_data_hitter_2 = pd.DataFrame(data = list(zip(team
                                          , HRA_RT
                                          , BB_CN
                                          ,IB_CN
                                          ,HP_CN
                                          ,KK_CN
                                          ,GD_CN
                                          ,SLG_RT
                                          ,OBP_RT
                                          ,OPS_RT
                                          ,MH_HITTER_CN
                                          ,SP_HRA_RT
                                          ,PH_HRA_RT
                                        )
                                      )
                        , columns = columns_all
                        ).set_index('팀명')


  return pd.concat([all_data_hitter_1,all_data_hitter_2],axis=1)

### ### 출력

In [10]:
getAllDataHitter(year = 2001)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:28: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:113: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead

,AVG,G,PA,AB,R,H,2B,3B,HR,TB,...,IBB,HBP,SO,GDP,SLG,OBP,OPS,MH,RISP,PH-BA
팀명,,,,,,,,,,,,,,,,,,,,,
롯데,0.280,133,5308,4521,718,1265,247,24,121,1923,...,39,60,817,89,0.425,0.365,0.790,133,0.288,0.244
KIA,0.278,133,5189,4542,683,1263,221,17,142,1944,...,21,56,774,129,0.428,0.353,0.781,133,0.272,0.225
삼성,0.277,133,5280,4553,739,1262,244,21,162,2034,...,27,95,814,111,0.447,0.360,0.807,133,0.267,0.223
두산,0.276,133,5303,4583,732,1266,221,26,130,1929,...,27,60,697,116,0.421,0.359,0.780,133,0.278,0.163
LG,0.276,133,5319,4521,669,1247,219,24,85,1769,...,24,52,759,100,0.391,0.363,0.754,133,0.280,0.263
한화,0.275,133,5259,4556,659,1255,211,15,148,1940,...,28,45,877,106,0.426,0.357,0.783,133,0.265,0.233
현대,0.268,133,5225,4445,711,1192,166,20,169,1905,...,14,76,911,109,0.429,0.362,0.791,133,0.279,0.232
SK,0.260,133,5077,4400,596,1143,215,11,113,1719,...,23,71,770,95,0.391,0.337,0.728,133,0.255,0.274

## ## [투수 데이터]

In [38]:
def getAllDataPitcher(year = 2022)  :
  """
  # year = 검색할 연도
  """
  driver.get("https://www.koreabaseball.com/Record/Team/Pitcher/Basic1.aspx")

  dropdown = Select(driver.find_element_by_id('cphContents_cphContents_cphContents_ddlSeason_ddlSeason'))
  dropdown.select_by_value(f"{year}")

  sleep(10)

  html = driver.page_source

  soup = BeautifulSoup(html, "html.parser")

  team = list()

  for i_team_list in range(1,len(soup.select("tr"))-1) :
    team_xpath = driver.find_element_by_xpath(f"//*[@id='cphContents_cphContents_cphContents_udpContent']/div[2]/table/tbody/tr[{i_team_list}]/td[2]")
    team.append(team_xpath.text)

  td_list_pitcher_1 = ["team"
                    , "ERA_RT"
                    , "GAME_CN"
                    , "W_CN"
                    , "L_CN"
                    , "SV_CN"
                    , "HOLD_CN"
                    , "WRA_RT"
                    , "INN2_CN"
                    , "HIT_CN"
                    , "HR_CN"
                    , "BB_CN"
                    , "HP_CN"
                    , "KK_CN"
                    , "R_CN"
                    , "ER_CN"
                    , "WHIP_RT"
                    ]
  ERA_RT = list()  
  GAME_CN = list()
  W_CN = list()
  L_CN = list()
  SV_CN = list()
  HOLD_CN = list()
  WRA_RT = list()
  INN2_CN = list()
  HIT_CN = list()
  HR_CN = list()
  BB_CN = list()
  HP_CN = list()
  KK_CN = list()
  R_CN = list()
  ER_CN = list()
  WHIP_RT = list()

  for idx in td_list_pitcher_1 :
    for i in range(len(soup.select(f"[data-id='{idx}']"))) :
      if idx == "GAME_CN" :
        GAME_CN.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "ERA_RT" :
        ERA_RT.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "W_CN" :
        W_CN.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "L_CN" :
        L_CN.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "SV_CN" :
        SV_CN.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "HOLD_CN" :
        HOLD_CN.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "WRA_RT" :
        WRA_RT.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "INN2_CN" :
        INN2_CN.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "HIT_CN" :
        HIT_CN.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "HR_CN" :
        HR_CN.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "BB_CN" :
        BB_CN.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "HP_CN" :
        HP_CN.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "KK_CN" :
        KK_CN.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "R_CN" :
        R_CN.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "ER_CN" :
        ER_CN.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "WHIP_RT" :
        WHIP_RT.append(soup.select(f"[data-id='{idx}']")[i].text)

  # 컬럼명 추출
  columns_all = list()

  for i in soup.select("th")[1:] :
    columns_all.append(i.text)

  all_data_pitcher_1 = pd.DataFrame(data = list(zip(team
                                                    , ERA_RT
                                                  , GAME_CN
                                                  , W_CN
                                                  , L_CN
                                                  , SV_CN
                                                  , HOLD_CN
                                                  , WRA_RT
                                                  , INN2_CN
                                                  , HIT_CN
                                                  , HR_CN
                                                  , BB_CN
                                                  , HP_CN
                                                  , KK_CN
                                                  , R_CN
                                                  , ER_CN
                                                  , WHIP_RT
                                                    )
  )
                                      , columns = columns_all
                                      ).set_index('팀명')
  

  driver.get("https://www.koreabaseball.com/Record/Team/Pitcher/Basic2.aspx")

  dropdown = Select(driver.find_element_by_id('cphContents_cphContents_cphContents_ddlSeason_ddlSeason'))
  dropdown.select_by_value(f"{year}")

  sleep(10)

  html = driver.page_source

  soup = BeautifulSoup(html, "html.parser")

  team = list()

  for i_team_list in range(1,len(soup.select("tr"))-1) :
    team_xpath = driver.find_element_by_xpath(f"//*[@id='cphContents_cphContents_cphContents_udpContent']/div[2]/table/tbody/tr[{i_team_list}]/td[2]")
    team.append(team_xpath.text)

  td_list_pitcher_2 = ["team"
                    , "ERA_RT"
                    , "CG_CN"
                    , "SHO_CN"
                    , "QS_CN"
                    , "BS_CN"
                    , "PA_CN"
                    , "PIT_CN"
                    , "OAVG_RT"
                    , "H2_CN"
                    , "H3_CN"
                    , "SH_CN"
                    , "SF_CN"
                    , "IB_CN"
                    , "WP_CN"
                    , "BK_CN"
                    ]
  ERA_RT = list()
  CG_CN= list()
  SHO_CN= list()
  QS_CN= list()
  BS_CN= list()
  PA_CN= list()
  PIT_CN= list()
  OAVG_RT= list()
  H2_CN= list()
  H3_CN= list()
  SH_CN= list()
  SF_CN= list()
  IB_CN= list()
  WP_CN= list()
  BK_CN= list()

  for idx in td_list_pitcher_2 :
    for i in range(len(soup.select(f"[data-id='{idx}']"))) :
      if idx == "CG_CN" :
        CG_CN.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "ERA_RT" :
        ERA_RT.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "SHO_CN" :
        SHO_CN.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "QS_CN" :
        QS_CN.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "BS_CN" :
        BS_CN.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "PA_CN" :
        PA_CN.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "PIT_CN" :
        PIT_CN.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "OAVG_RT" :
        OAVG_RT.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "H2_CN" :
        H2_CN.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "H3_CN" :
        H3_CN.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "SH_CN" :
        SH_CN.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "SF_CN" :
        SF_CN.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "IB_CN" :
        IB_CN.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "WP_CN" :
        WP_CN.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "BK_CN" :
        BK_CN.append(soup.select(f"[data-id='{idx}']")[i].text)
  
  # 컬럼명 추출
  columns_all = list()

  for i in soup.select("th")[1:] :
    columns_all.append(i.text)

  all_data_pitcher_2 = pd.DataFrame(data = list(zip(team
                                                    , ERA_RT
                                                      ,CG_CN
                                                      ,SHO_CN
                                                      ,QS_CN
                                                      ,BS_CN
                                                      ,PA_CN
                                                      ,PIT_CN
                                                      ,OAVG_RT
                                                      ,H2_CN
                                                      ,H3_CN
                                                      ,SH_CN
                                                    ,  SF_CN
                                                    , IB_CN
                                                    , WP_CN
                                                    , BK_CN
                                                    )
  )
                                      , columns = columns_all
                                      ).set_index('팀명')
  
  return pd.concat([all_data_pitcher_1,all_data_pitcher_2],axis=1)

### ### 출력

In [39]:
getAllDataPitcher()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  import sys
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:19: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:123: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:135: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead

,ERA,G,W,L,SV,HLD,WPCT,IP,H,HR,...,TBF,NP,AVG,2B,3B,SAC,SF,IBB,WP,BK
팀명,,,,,,,,,,,,,,,,,,,,,
키움,3.21,39,21,18,11,23,0.538,353 2/3,304,16,...,1488,5783,0.232,81,6,12,13,4,21,0
롯데,3.25,38,20,17,9,22,0.541,343 1/3,314,14,...,1460,5710,0.243,59,4,13,10,4,18,1
두산,3.27,37,20,16,12,24,0.556,335 2/3,297,20,...,1435,5555,0.239,52,1,19,14,4,18,1
삼성,3.38,38,20,18,10,17,0.526,336,335,29,...,1446,5558,0.258,66,1,22,8,5,19,2
KIA,3.38,38,19,19,10,18,0.500,333,311,24,...,1424,5420,0.244,63,9,15,14,4,22,2
SSG,3.42,39,25,12,16,31,0.676,355 2/3,296,24,...,1477,5672,0.225,48,3,12,8,8,20,2
KT,3.49,38,17,21,9,16,0.447,337 2/3,336,24,...,1414,5396,0.261,40,7,10,13,6,14,0
LG,3.55,39,23,16,12,24,0.590,350 1/3,318,24,...,1497,5841,0.244,54,10,12,15,6,13,0
NC,4.53,39,12,27,7,9,0.308,343 1/3,360,27,...,1551,6066,0.268,63,8,13,10,5,30,2
한화,4.97,39,13,26,8,20,0.333,337,369,32,...,1525,5924,0.278,80,5,16,15,6,15,1

## ## [수비 데이터]

In [40]:
def getAllDataDefence(year = 2022) :
  """
  # year = 검색할 연도
  """
  driver.get("https://www.koreabaseball.com/Record/Team/Defense/Basic.aspx")

  dropdown = Select(driver.find_element_by_id('cphContents_cphContents_cphContents_ddlSeason_ddlSeason'))
  dropdown.select_by_value(f"{year}")

  sleep(10)

  html = driver.page_source

  soup = BeautifulSoup(html, "html.parser")

  team = list()

  for i_team_list in range(1,len(soup.select("tr"))-1) :
    team_xpath = driver.find_element_by_xpath(f"//*[@id='cphContents_cphContents_cphContents_udpContent']/div[2]/table/tbody/tr[{i_team_list}]/td[2]")
    team.append(team_xpath.text)

  td_list_defence_1 = ["team"
                    , "GAME_CN"
                    , "ERR_CN"
                    , "POFF_CN"
                    , "PO_CN"
                    , "ASS_CN"
                    , "GDP_CN"
                    , "FPCT_RT"
                    , "PB_CN"
                    , "SB_CN"
                    , "CS_CN"
                    , "CS_RT"
                    ]
  GAME_CN = list()
  ERR_CN = list()
  POFF_CN = list()
  PO_CN = list()
  ASS_CN = list()
  GDP_CN = list()
  FPCT_RT = list()
  PB_CN = list()
  SB_CN = list()
  CS_CN = list()
  CS_RT = list()

  for idx in td_list_defence_1 :
    for i in range(len(soup.select(f"[data-id='{idx}']"))) :
      if idx == "GAME_CN" :
        GAME_CN.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "ERR_CN" :
        ERR_CN.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "POFF_CN" :
        POFF_CN.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "PO_CN" :
        PO_CN.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "ASS_CN" :
        ASS_CN.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "GDP_CN" :
        GDP_CN.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "FPCT_RT" :
        FPCT_RT.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "PB_CN" :
        PB_CN.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "SB_CN" :
        SB_CN.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "CS_CN" :
        CS_CN.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "CS_RT" :
        CS_RT.append(soup.select(f"[data-id='{idx}']")[i].text)

  # 컬럼명 추출
  columns_all = list()

  for i in soup.select("th")[1:] :
    columns_all.append(i.text)

  all_data_defence_1 = pd.DataFrame(data = list(zip(team
                                                  , GAME_CN
                                                  , ERR_CN
                                                  , POFF_CN
                                                  , PO_CN
                                                  , ASS_CN
                                                  , GDP_CN
                                                  , FPCT_RT
                                                  , PB_CN
                                                  , SB_CN
                                                  , CS_CN
                                                  , CS_RT
                                                    )
  )
                                      , columns = columns_all
                                      ).set_index('팀명')

  return all_data_defence_1

### ### 출력

In [41]:
getAllDataDefence()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  import sys
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:19: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead

      G   E PKO    PO    A  DP   FPCT PB  SB  CS   CS%
팀명
SSG  39  23   1  1067  407  37  0.985  0  40   4   9.1
키움   39  29   1  1061  460  38  0.981  3  15  11  42.3
LG   39  25   0  1051  386  36  0.983  3  43  10  18.9
NC   39  42   2  1030  369  29  0.971  6  24  14  36.8
롯데   38  34   1  1030  381  36  0.976  2  27  13  32.5
KT   38  29   8  1013  378  35  0.980  3  22   7  24.1
한화   39  43   2  1011  374  23  0.970  3  31  16  34.0
삼성   38  37   0  1008  384  32  0.974  2  11   9  45.0
두산   37  39   1  1007  357  41  0.972  3  23   8  25.8
KIA  38  37   1   999  348  19  0.973  3  17   9  34.6

## ## [주루 데이터]

In [42]:
def getAllDataRunner(year = 2022) :
  """
  # year = 검색할 연도
  """
  driver.get("https://www.koreabaseball.com/Record/Team/Runner/Basic.aspx")

  dropdown = Select(driver.find_element_by_id('cphContents_cphContents_cphContents_ddlSeason_ddlSeason'))
  dropdown.select_by_value(f"{year}")

  sleep(10)

  html = driver.page_source

  soup = BeautifulSoup(html, "html.parser")

  team = list()

  for i_team_list in range(1,len(soup.select("tr"))-1) :
    team_xpath = driver.find_element_by_xpath(f"//*[@id='cphContents_cphContents_cphContents_udpContent']/div[2]/table/tbody/tr[{i_team_list}]/td[2]")
    team.append(team_xpath.text)

  td_list_runner_1 = ["team"
                    , "GAME_CN"
                    , "SBA_CN"
                    , "SB_CN"
                    , "CS_CN"
                    , "SB_RT"
                    , "RO_CN"
                    , "POFF_CN"
                    ]

  GAME_CN = list()
  SBA_CN = list()
  SB_CN = list()
  CS_CN = list()
  SB_RT = list()
  RO_CN = list()
  POFF_CN = list()

  for idx in td_list_runner_1 :
    for i in range(len(soup.select(f"[data-id='{idx}']"))) :
      if idx == "GAME_CN" :
        GAME_CN.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "SBA_CN" :
        SBA_CN.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "SB_CN" :
        SB_CN.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "CS_CN" :
        CS_CN.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "SB_RT" :
        SB_RT.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "RO_CN" :
        RO_CN.append(soup.select(f"[data-id='{idx}']")[i].text)
      elif idx == "POFF_CN" :
        POFF_CN.append(soup.select(f"[data-id='{idx}']")[i].text)

  # 컬럼명 추출
  columns_all = list()

  for i in soup.select("th")[1:] :
    columns_all.append(i.text)

  all_data_runner_1 = pd.DataFrame(data = list(zip(team
                                                  ,GAME_CN
                                                  ,SBA_CN
                                                  ,SB_CN
                                                  ,CS_CN
                                                  ,SB_RT
                                                  ,RO_CN
                                                  ,POFF_CN
                                                    )
  )
                                      , columns = columns_all
                                      ).set_index('팀명')

  return all_data_runner_1

### ### 출력

In [43]:
getAllDataRunner()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  import sys
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:19: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead

      G SBA  SB  CS   SB% OOB PKO
팀명
두산   37  45  37   8  82.2  12   0
삼성   38  43  34   9  79.1  11   4
한화   39  43  33  10  76.7  13   2
KT   38  39  30   9  76.9  10   1
LG   39  44  30  14  68.2  13   1
키움   39  31  25   6  80.6  11   2
SSG  39  31  20  11  64.5  14   1
KIA  38  28  20   8  71.4  14   3
NC   39  32  19  13  59.4  13   1
롯데   38  28  15  13  53.6  12   2

# # 모두 합치기

## ## 기본

In [44]:
defence = getAllDataDefence()
runner = getAllDataRunner()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  import sys
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:19: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead

In [45]:
runner

      G SBA  SB  CS   SB% OOB PKO
팀명
두산   37  45  37   8  82.2  12   0
삼성   38  43  34   9  79.1  11   4
한화   39  43  33  10  76.7  13   2
KT   38  39  30   9  76.9  10   1
LG   39  44  30  14  68.2  13   1
키움   39  31  25   6  80.6  11   2
SSG  39  31  20  11  64.5  14   1
KIA  38  28  20   8  71.4  14   3
NC   39  32  19  13  59.4  13   1
롯데   38  28  15  13  53.6  12   2

In [46]:
df_all = pd.concat( (defence
                   , runner)
                   #, sort = False
                   ,axis = 1
                   ,ignore_index = False 

                   )
df_all

,G,E,PKO,PO,A,DP,FPCT,PB,SB,CS,CS%,G,SBA,SB,CS,SB%,OOB,PKO
팀명,,,,,,,,,,,,,,,,,,
SSG,39,23,1,1067,407,37,0.985,0,40,4,9.1,39,31,20,11,64.5,14,1
키움,39,29,1,1061,460,38,0.981,3,15,11,42.3,39,31,25,6,80.6,11,2
LG,39,25,0,1051,386,36,0.983,3,43,10,18.9,39,44,30,14,68.2,13,1
NC,39,42,2,1030,369,29,0.971,6,24,14,36.8,39,32,19,13,59.4,13,1
롯데,38,34,1,1030,381,36,0.976,2,27,13,32.5,38,28,15,13,53.6,12,2
KT,38,29,8,1013,378,35,0.980,3,22,7,24.1,38,39,30,9,76.9,10,1
한화,39,43,2,1011,374,23,0.970,3,31,16,34.0,39,43,33,10,76.7,13,2
삼성,38,37,0,1008,384,32,0.974,2,11,9,45.0,38,43,34,9,79.1,11,4
두산,37,39,1,1007,357,41,0.972,3,23,8,25.8,37,45,37,8,82.2,12,0
KIA,38,37,1,999,348,19,0.973,3,17,9,34.6,38,28,20,8,71.4,14,3

### ### 적용

In [47]:
def time_df() :
  import time
  from tqdm import tqdm

  start = time.time()

  for i in tqdm(range(1,6)):

    if i == 1 :
      hitter = getAllDataHitter()
      now = time.time()
      print(f'\r{i}/5 runtime: {now - start:.2f}')
      time.sleep(0.5)

    elif i == 2 :
      pitcher = getAllDataPitcher()
      now = time.time()
      print(f'\r{i}/5 runtime: {now - start:.2f}')
      time.sleep(0.5)

    elif i == 3 :
      defence = getAllDataDefence()
      now = time.time()
      print(f'\r{i}/5 runtime: {now - start:.2f}')
      time.sleep(0.5)

    elif i == 4 :
      runner = getAllDataRunner()
      now = time.time()
      print(f'\r{i}/5 runtime: {now - start:.2f}')
      time.sleep(0.5)

    elif i == 5 :
      df_all = pd.concat([hitter
                        ,pitcher
                        ,defence
                        ,runner]
                        , axis=1
                        )

      now = time.time()
      print(f'\r{i}/5 runtime: {now - start:.2f}')
      time.sleep(0.5)
    
    # 진행률
    msg = '\r진행률 %d %%' % (i/len(range(1,6))*100)
    print()
    print(msg)

  
  df_all.to_csv("/content/drive/MyDrive/Colab Notebooks/크롤링/kbo 데이터 크롤링/최종 결과물/df_all.csv")
  return df_all

# # 최종 결과

In [50]:
tmp=time_df()

  0%|          | 0/5 [00:00<?, ?it/s]/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:28: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:113: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead

1/5 runtime: 23.60

 20%|██        | 1/5 [00:24<01:36, 24.10s/it]

진행률 20 %

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  import sys
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:19: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:123: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:135: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead

2/5 runtime: 47.18

 40%|████      | 2/5 [00:47<01:11, 23.79s/it]

진행률 40 %
3/5 runtime: 59.03

 60%|██████    | 3/5 [00:59<00:36, 18.34s/it]

진행률 60 %
4/5 runtime: 70.86

 80%|████████  | 4/5 [01:11<00:15, 15.77s/it]

진행률 80 %
5/5 runtime: 71.37

100%|██████████| 5/5 [01:11<00:00, 14.37s/it]

진행률 100 %